### ISSUE TITLE
socket hang up error whenever incoming post arrives at the server

### ISSUE THREAD

**Issue by mountaindude** [femto113/node-ifttt-webhook#2]
Running the service on OSX, but whenever an incoming call from IFTTT arrives, the service throws an error "socket hang up". 
Any ideas? 
I've been poking around the code a bit, no real luck though.
Error messages follow.

> node server.js

listening on port 80
deserialized: mt.supportedMethods([0])
deserialized: metaWeblog.getRecentPosts([0,"node-gw","123",1])
deserialized: metaWeblog.getRecentPosts([0,"node-gw","123",1])
deserialized: mt.supportedMethods([0])
deserialized: metaWeblog.getRecentPosts([0,"node-gw","123",1])
deserialized: metaWeblog.getRecentPosts([0,"node-gw","123",1])

deserialized: metaWeblog.getCategories([0,"node-gw","123"])
deserialized: metaWeblog.newPost(["","node-gw","123",{"title":"March 20, 2015 at 07:32PM","description":"http://ift.tt/1C6ePFf","categories":["cat1","cat2","cat3"],"mt_keywords":["tag1"],"post_status":"publish"},true])

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: socket hang up
    at createHangUpError (http.js:1477:15)
    at Socket.socketOnEnd [as onend](http.js:1573:23)
    at Socket.g (events.js:180:16)
    at Socket.emit (events.js:117:20)
    at _stream_readable.js:944:16
    at process._tickCallback (node.js:442:13)

npm ERR! Darwin 14.0.0
npm ERR! argv "node" "/usr/local/bin/npm" "start"
npm ERR! node v0.10.36
npm ERR! npm  v2.7.1
npm ERR! code ELIFECYCLE
npm ERR! ifttt-webhook@0.0.0 start: `node server.js`
npm ERR! Exit status 8
npm ERR!
npm ERR! Failed at the ifttt-webhook@0.0.0 start script 'node server.js'.
npm ERR! This is most likely a problem with the ifttt-webhook package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node server.js
npm ERR!     npm owner ls ifttt-webhook
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/goran/code/node-ifttt-webhook/npm-debug.log

**Comment by femto113** [comment]
Server is expecting the URL of the webhook in the mt_keywords field, looks like you're sending it in the description.  I've updated the test.js script to show this a little clearer, try running it to see how it does (it simulates the role of IFTTT in the process).
